[package]
name = "platform"
version = "0.1.0"
authors = ["Maxim Bogdanov <maxim.bogdanov@coins.ph>"]
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["lib"]

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3

[dependencies]
common = { path = "../common" }
metadata = { path = "../metadata" }
actix-http = { version = "3.0.0-beta.18", default-features = false, features = [
	"openssl",
	"rustls",
	"compress-brotli",
	"compress-gzip",
] }
actix-service = "2.0.2"
actix-utils = "3.0.0"
actix-web = { version = "4.0.0-beta.19", default-features = false, features = [
	"compress-brotli",
	"compress-gzip",
	"cookies",
] }
futures = "0.3.19"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
chrono = { version = "0.4.19", features = ["serde"] }
arrow = "5.2.0"
datafusion = "6.0.0"
tokio = { version = "1.15.0", features = [
	"macros",
	"rt",
	"rt-multi-thread",
	"sync",
] }
async-trait = "0.1.52"
rocksdb = { version = "0.17.0", features = ["multi-threaded-cf"] }
jsonwebtoken = "7.2.0"
lazy_static = "1.4.0"
rand = "0.8.4"
sha3 = "0.10.0"
hex = "0.4.3"
bincode = "1.3.3"
parking_lot = "0.11.2"
mockall = "0.11.0"

[dev-dependencies]
criterion = "0.3.5"

# [[bench]]
# name = "count"
# harness = false

#[[bench]]
#name = "dictionary"
#harness = false
